version: '3.8'

services:
  proxy:
    container_name: proxy
    restart: on-failure
    build:
      dockerfile: docker/file_proxy/Dockerfile
      context: .
    volumes:
      - ./poetry.lock:/service/poetry.lock
      - ./pyproject.toml:/service/pyproject.toml
